.TH "wmail" "1" "1.3.8" "Raúl Romero García aka bgta" "openSUSE Build Service home project"
.SH "NAME"
\fBWMail\fR adds loads of features that mail on the web misses making your mail feel right at home on your computer. It's easy to use, fast and has all the features you're already enjoying on the web.
.br
.SH "SEE ALSO"
\fIhttps://thomas101.github.io/wmail/\fR
.br
